# Change these first
owner: incarnatewill # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Raphtalia
    check: "tcp-ping"
    url: main.raphtalia.fun
    port: 22223
  - name: Webserver
    check: "tcp-ping"
    url: ws.raphtalia.fun
    port: 22223
  - name: Ge-1
    check: "tcp-ping"
    url: ge1.raphtalia.fun
    port: 20029
  - name: Ge-2
    check: "tcp-ping"
    url: ge2.raphtalia.fun
    port: 32324
  - name: Ge-3
    check: "tcp-ping"
    url: ge3.raphtalia.fun
    port: 25571
  - name: Us-1
    check: "tcp-ping"
    url: us1.raphtalia.fun
    port: 2124
  - name: As-1
    check: "tcp-ping"
    url: as1.raphtalia.fun
    port: 3000

i18n:
  footer: Join the [Support server](https://discord.gg/zjuy7tMqtz)

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.raphtalia.fun
  logoUrl: https://res.cloudinary.com/teepublic/image/private/s--FT3uHZOx--/c_fit,g_north_west,h_798,w_840/co_000000,e_outline:40/co_000000,e_outline:inner_fill:1/co_ffffff,e_outline:40/co_ffffff,e_outline:inner_fill:1/co_bbbbbb,e_outline:3:1000/c_mpad,g_center,h_1260,w_1260/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1555441707/production/designs/4652846_0.jpg
  name: Raphtalia
  introTitle: "**Raphtalia uptime monitor**"
  status-website:
  theme: ocean
  introMessage: Check the uptime of the bot and the Lavalink servers
  navbar:
    - title: Status
      href: /
